version: 2
updates:

  # Security updates only.
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 0
    labels:
      - "chore"
      - "dependencies"
      - "security"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
    cooldown:
      default-days: 10
    open-pull-requests-limit: 10
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
    commit-message:
      prefix: "ci"
    labels:
      - "chore"
      - "dependencies"
      - "github_actions"
