name: Release Wheels

permissions: write-all

on:
  release:
    types: [created, published]

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - uses: prefix-dev/setup-pixi@v0.6.0
      #   with:
      #     pixi-version: v0.21.1
      #    cache: true
      #    frozen: true

      # - name: Build a binary wheel and a source tarball
      #   run: pixi run -e dev python3 -m build --sdist --wheel --outdir dist/ .

      # - name: Check distribution files
      #   run: pixi run -e dev python3 -m twine check dist/*

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      - name: Install pypa/build
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build twine --user

      - name: Build a binary wheel and a source tarball
        run: python3 -m build --sdist --wheel --outdir dist/ .

      - name: Check distribution files
        run: twine check dist/*

      # if it matches a Python release tag, upload to github releases
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
